namespace WiFiRemote {
  char *htmlConfigIndex = "<html>"
    "  <head>"
    "   <title>WiFi Remote - WiFi Settings</title>"
    "   <script type=\"text/javascript\">"
    "     function httpGetAsync(theUrl, headers, callback) {"
    "         var xmlHttp = new XMLHttpRequest();"
    "         xmlHttp.onreadystatechange = function() { "
    "             if (xmlHttp.readyState == 4 && xmlHttp.status == 200)"
    "                 callback(xmlHttp.responseText);"
    "         }"
    "         xmlHttp.open(\"GET\", theUrl, true);"
    "         xmlHttp.setRequestHeader(\"Cache-Control\", \"no-cache\");"
    "         "
    "         if(headers != null) {"
    "           for(i = 0; i < headers.length; i++) {"
    "             xmlHttp.setRequestHeader(headers[i].name, headers[i].value);"
    "           }"
    "         }"
    ""
    "         xmlHttp.send(null);"
    "     }"
    "     function getSSIDs() {"
    "       setStatus(\"Scanning...\");"
    "       httpGetAsync(\"station_scan\", null, function(stations) {"
    "         updateSSIDs(stations);"
    ""
    "         setStatus("");"
    "       });"
    "     }"
    ""
    "     function updateSSIDs(stations) {"
    "       var select = document.getElementById(\"SSID_SEL\");"
    "       "
    "       while(select.firstChild) {"
    "         select.removeChild(select.firstChild);"
    "       }"
    "       "
    "       var stationObj = JSON.parse(stations);"
    "       var arr = stationObj.Stations;"
    ""
    "       for(i = 0; i < arr.length; i++) {"
    "         var newOpt = document.createElement('option');"
    "         newOpt.text = arr[i].SSID;"
    "         newOpt.value = arr[i].SSID;"
    "         select.append(newOpt);"
    "       }"
    "     }"
    ""
    "     function validatePSK() {"
    "       var psk = document.getElementById(\"PSK\").value;"
    ""
    "       if(psk.length < 8 || psk.length > 63) {"
    "         alert(\"WiFi PSK must be between 8 and 63 characters\");"
    "         return false;"
    "       }"
    "       else {"
    "         return true;"
    "       }"
    "     }"
    ""
    "     function tryConnect() {"
    "       if(validatePSK()) {"
    "         setStatus(\"Connecting...\", null);"
    ""
    "         headers = ["
    "           {"
    "             \"name\" : \"psk\","
    "             \"value\" : document.getElementById(\"PSK\").value"
    "           },"
    "           {"
    "             \"name\" : \"ssid\","
    "             \"value\" : document.getElementById(\"SSID_SEL\").value"
    "           }"
    "         ]"
    "         httpGetAsync(\"try_connect\", headers, function(result) {"
    "           var parsed = JSON.parse(result);"
    "           if(parsed.success == \"true\") {"
    "             window.location.href = \"/config_server.html\";"
    "           }"
    "           else {"
    "             setStatus(\"Connect Failed\", \"red\");"
    "           }"
    "         });"
    "       }"
    "       "
    "       return false;"
    "     }"
    ""
    "     function setStatus(text, color) {"
    "       var statusNode = document.getElementById(\"status_text\");"
    "       if(color == null) {"
    "         color = \"black\";"
    "       }"
    "       statusNode.innerHTML = \"<font size=2 color=\" + color + \">\" + text + \"</font>\";"
    "     }"
    "   </script>"
    " </head>"
    " <body>"
    " <center>"
    "   <form onsubmit=\"return tryConnect()\">"
    "     <style type=\"text/css\">"
    "       .fieldset-auto-width {"
    "         display: inline-block;"
    "       }"
    "     </style>"
    "     <fieldset style=\"width:0px\">"
    "       <legend>Access Point</legend>"
    "       SSID:<br>"
    "       <select name=\"ssid\" id=\"SSID_SEL\">"
    "       </select>"
    "       <button type=\"button\" onclick=\"getSSIDs()\">Scan</button>"
    "       <p>"
    "       PSK:<br>"
    "       <input type=\"password\" name=\"psk\" id=\"PSK\"><br>"
    "       <input type=\"submit\" value=\"Connect\">"
    "       <p id=\"status_text\"> </p>"
    "     </fieldset>"
    "   </form>"
    ""
    "   <script type=\"text/javascript\">"
    "     getSSIDs();"
    "   </script>"
    " </center>"
    " </body>"
    "</html>";

  char* htmlConfigServer = "<html>"
    " <head>"
    "   <title>WiFi Remote - Server Settings</title>"
    "   <script type=\"text/javascript\">"
    "     var serverConfig;"
    ""
    "     function httpGetAsync(theUrl, headers, callback) {"
    "         var xmlHttp = new XMLHttpRequest();"
    "         xmlHttp.onreadystatechange = function() { "
    "             if (xmlHttp.readyState == 4 && xmlHttp.status == 200)"
    "                 callback(xmlHttp.responseText);"
    "         }"
    "         xmlHttp.open(\"GET\", theUrl, true);"
    "         xmlHttp.setRequestHeader(\"Cache-Control\", \"no-cache\");"
    "         "
    "         if(headers != null) {"
    "           for(i = 0; i < headers.length; i++) {"
    "             xmlHttp.setRequestHeader(headers[i].name, headers[i].value);"
    "           }"
    "         }"
    ""
    "         xmlHttp.send(null);"
    "     }"
    "     function getConfig() {"
    "       setStatus(\"Loading Server Config...\");"
    "       httpGetAsync(\"server_config\", null, function(response) {"
    "         setConfig(JSON.parse(response));"
    ""
    "         setStatus("");"
    "       });"
    "     }"
    ""
    "     function setConfig(config) {"
    "       serverConfig = config;"
    "       "
    "       document.getElementById(\"legend\").innerHTML = config.EventName;"
    ""
    "       var divisions = config.Divisions;"
    "       if(divisions.length > 1) {"
    "         var select = document.createElement(\"select\");"
    "         select.name = \"Division\";"
    "         select.id = \"division\";"
    "         select.onchange = updateFieldOptions;"
    "         "
    "         for(i = 0; i < divisions.length; i++) {"
    "           var option = document.createElement(\"option\");"
    "           option.text = config.Divisions[i].Name;"
    "           option.value = option.text;"
    "           select.append(option);"
    "         }"
    "         var division_select = document.getElementById(\"division_select\");"
    "         division_select.innerHTML = "";"
    "         division_select.append(select);"
    "       }"
    ""
    "       updateFieldOptions();"
    "     }"
    ""
    "     function updateFieldOptions() {"
    "       var controls = document.getElementById(\"field_controls\");"
    "       controls.innerHTML = "";"
    "       "
    "       var division;"
    "       var divisions = serverConfig.Divisions;"
    "       if(divisions.length > 1) {"
    "         var selected = document.getElementById(\"division\").value;"
    ""
    "         for(i = 0; i < divisions.length; i++) {"
    "           if(divisions[i].Name == selected) {"
    "             division = divisions[i];"
    "             break;"
    "           }"
    "         }"
    "       }"
    "       else {"
    "         division = divisions[0];"
    "       }"
    ""
    "       var check1 = document.createElement(\"input\");"
    "       check1.type = \"checkbox\";"
    "       check1.id = \"check_1\";"
    "       var label1 = document.createElement(\"label\");"
    "       label1.htmlFor = \"check_1\";"
    "       label1.innerHTML = \"Field 1\";"
    ""
    ""
    "       if(division.NumFields == 1) {"
    "         check1.checked = true;"
    "         check1.onclick = function() { return false; };"
    "         check1.onkeydown = function() { return false; };"
    "         "
    "         controls.append(check1);"
    "         controls.append(label1);"
    "       }"
    "       else {"
    "         var check2 = document.createElement(\"input\");"
    "         check2.type = \"checkbox\";"
    "         check2.id = \"check_2\";"
    "         var label2 = document.createElement(\"label\");"
    "         label2.htmlFor = \"check_2\";"
    "         label2.innerHTML = \"Field 2\";"
    ""
    "         controls.append(check1);"
    "         controls.append(label1);"
    "         controls.append(check2);"
    "         controls.append(label2);"
    "       }"
    "     }"
    ""
    "     function setStatus(text, color) {"
    "       var statusNode = document.getElementById(\"status_text\");"
    "       if(color == null) {"
    "         color = \"black\";"
    "       }"
    "       statusNode.innerHTML = \"<font size=2 color=\" + color + \">\" + text + \"</font>\";"
    "     }"
    ""
    "     function tryRegister() {"
    "       var headers = {};"
    ""
    "       headers.fields = [];"
    "       "
    "       var checkBox1 = document.getElementById(\"check_1\");"
    "       var checkBox2 = document.getElementById(\"check_2\");"
    ""
    "       var check1 = checkBox1.checked;"
    "       var check2 = false;"
    "       if(checkBox2) {"
    "         check2 = checkBox2.checked;"
    "       }"
    "       "
    "       if(!check1 && !check2) {"
    "         alert(\"At least one field must be selected\");"
    "       }"
    "       else {"
    "         setStatus(\"Registering...\", null);"
    ""
    "         if(check1) {"
    "           headers.fields.push(1);"
    "         }"
    "         if(check2) {"
    "           headers.fields.push(2);"
    "         }"
    ""
    "         if(serverConfig.Divisions.length > 1) {"
    "           headers.division = document.getElementById(\"division\").value;"
    "         }"
    ""
    "         httpGetAsync(\"/try_register\", headers, function(result) {"
    "           if(JSON.parse(result).success == \"true\") {"
    "             window.location.href = \"/config_done.html\";"
    "           }"
    "           else {"
    "             setStatus(\"Registration Failed\", \"red\");"
    "           }"
    "         });"
    "       }"
    ""
    "       return false;"
    "     }"
    "   </script>"
    " </head>"
    " <body>"
    " <center>"
    "   <form onsubmit=\"return tryRegister()\">"
    "     <fieldset id=\"fieldset\" style=\"width:0px\">"
    "       <legend id=\"legend\"> </legend>"
    "       <p><div id=\"division_select\">"
    "       </div></p>"
    "       <p><div id=\"field_controls\">"
    "       </div></p>"
    "       <p>"
    "       <input type=\"submit\" value=\"Register\">"
    "       </p>"
    "       <p id=\"status_text\"> </p>"
    "     </fieldset>"
    "   </form>"
    ""
    "   <script type=\"text/javascript\">"
    "     getConfig();"
    "   </script>"
    " </center>"
    " </body>"
    "</html>";

  char *htmlConfigDone = "<html>"
    " <head>"
    "   <title>WiFi Remote - Done</title>"
    " </head>"
    ""
    " <body>"
    " <center>"
    "   <h1>Configuration Done</h1>"
    "   <p>To change device configuration, restart device in configuration mode</p>"
    " </center>"
    " </body>"
    "</html>";
}

